import{a as g,S as h,i as n}from"./assets/vendor-Dt0HiiXr.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const y="49169306-de27c58c14ea5b5fada8fc03c",b="https://pixabay.com/api/",L=i=>g.get(b,{params:{key:y,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data.hits).catch(t=>{iziToast.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error(t)}),u=document.querySelector(".gallery"),v=()=>{u.innerHTML=""},q=i=>{const t=i.map(({webformatURL:a,largeImageURL:e,tags:r,likes:s,views:p,comments:f,downloads:m})=>`<a class="gallery-item" href="${e}">
          <div class="photo-card">
            <img src="${a}" alt="${r}" />
            <div class="info">
              <p><b>Likes:</b> ${s}</p>
              <p><b>Views:</b> ${p}</p>
              <p><b>Comments:</b> ${f}</p>
              <p><b>Downloads:</b> ${m}</p>
            </div>
          </div>
        </a>`).join("");u.insertAdjacentHTML("beforeend",t),new h(".gallery a").refresh()},c=document.querySelector(".form"),w=document.querySelector(".form-input"),d=document.querySelector(".loader");function P(){d.classList.add("active")}function l(){d.classList.remove("active")}c.addEventListener("submit",i=>{i.preventDefault();const t=w.value.trim();if(!t){n.warning({message:"Please enter a valid search query!",position:"topRight"});return}v(),P(),L(t).then(o=>{if(l(),o.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c.reset();return}q(o),c.reset()}).catch(o=>{l(),n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error(o)})});
//# sourceMappingURL=index.js.map
